export const PRIVACY_POLICY_HTML = `
  <p>Welcome to Stars Base. We value your privacy and are committed to protecting your personal data. This Privacy Policy explains what information we collect, why we collect it, how we use and share it, how long we retain it, and how you can exercise rights available under applicable law when using Stars Base services (the “Services”), including our Telegram Mini App, bot, dashboard, website, APIs, and related interfaces.</p>

  <p>By accessing or using Stars Base (referred to as “Stars Base”, “we”, “our” or “us”), you acknowledge and accept the practices described in this Privacy Policy.</p>

  <h3>1. Scope and purpose</h3>
  <ol>
    <li>
      <p>This Privacy Policy applies to personal data collected from users of Stars Base across our Telegram Mini App, bot, website, APIs, and support channels.</p>
    </li>
    <li>
      <p>This Policy explains:</p>
      <ol type="A">
        <li>What categories of personal data we collect and why;</li>
        <li>How we collect, use, and share personal data;</li>
        <li>How long we retain personal data;</li>
        <li>The rights available to you regarding your personal data and how to exercise them via the in-app mechanisms; and</li>
        <li>Our security practices and operational safeguards.</li>
      </ol>
    </li>
    <li>
      <p>We process personal data to provide and improve the Services, to meet legal and regulatory obligations, to protect the platform and users from fraud and abuse, and where lawful, to communicate product updates and optional offers.</p>
    </li>
  </ol>

  <h3>2. Categories of data we collect</h3>
  <ol>
    <li>
      <p>We limit collection to the minimum personal data necessary to operate and secure the Services. Categories of personal data we may collect include:</p>
      <ol type="A">
        <li>
          <strong>Data you provide directly:</strong> Telegram identifiers (username, display name, Telegram ID), optional contact information you elect to share, transaction records (staking, deposits, withdrawals, conversions), and support correspondence. Identity verification documents may be collected only where required by law or necessary for compliance.
        </li>
        <li>
          <strong>Data generated by your activity:</strong> usage and engagement data (features used, timestamps), device and connection information (device type, operating system, IP address), in-app telemetry and logs, and aggregated or anonymized metadata.
        </li>
        <li>
          <strong>Data from third parties:</strong> information received from trusted service providers (payment processors, analytics providers, identity verification services) and permitted public sources.
        </li>
      </ol>
    </li>
    <li>
      <p>We do not knowingly collect personal data from individuals under 18. If you are under 18, do not provide personal data to Stars Base.</p>
    </li>
  </ol>

  <h3>3. How we collect personal data</h3>
  <ol>
    <li>
      <p>We collect personal data when you:</p>
      <ol type="A">
        <li>Use the Stars Base Mini App or bot;</li>
        <li>Register, authenticate, or connect your Telegram account to the Services;</li>
        <li>Perform staking deposits, withdrawals, conversions, or other transactions;</li>
        <li>Interact with support workflows, surveys, or feedback mechanisms; and</li>
        <li>Visit our website or interact with our marketing content.</li>
      </ol>
    </li>
    <li>
      <p>We also collect information automatically through cookies, web beacons, local storage, and similar technologies on our website and certain interfaces. See Section 9 (Cookies & Analytics).</p>
    </li>
    <li>
      <p>When we obtain data from third parties, we require those providers to meet applicable data protection standards.</p>
    </li>
  </ol>

  <h3>4. Purposes of processing and legal bases</h3>
  <ol>
    <li>
      <p>We process personal data for the following purposes and legal bases:</p>
      <ol type="A">
        <li><strong>To provide and operate the Services (performance of contract):</strong> account management, transaction execution, reward calculation and distribution, and related platform features.</li>
        <li><strong>To satisfy legal and regulatory obligations (legal obligation):</strong> including anti-money laundering, taxation and regulatory reporting.</li>
        <li><strong>For fraud prevention, platform security and integrity (legitimate interest):</strong> detecting and preventing abuse, unauthorized access and harmful activity.</li>
        <li><strong>To improve and personalize the Services (legitimate interest or consent where required):</strong> product analytics, feature optimization and optional personalized notifications.</li>
        <li><strong>For marketing and communications (consent or legitimate interest where permitted):</strong> to send product updates, announcements or offers where you have consented or where lawful.</li>
      </ol>
    </li>
    <li>
      <p>We will not use your data for purposes incompatible with those described above without providing notice and obtaining consent if required.</p>
    </li>
  </ol>

  <h3>5. Sharing and disclosure</h3>
  <ol>
    <li>
      <p>We share personal data only as required to deliver and secure the Services:</p>
      <ol type="A">
        <li>With service providers who process data on our behalf under contract (payment processors, hosting providers, analytics and identity verification vendors);</li>
        <li>With law enforcement, courts or regulators where required by law or valid legal process;</li>
        <li>With parties involved in investigations of fraud, abuse or security incidents;</li>
        <li>In connection with a corporate transaction such as a merger, sale, reorganization or asset transfer, provided that any acquirer will be subject to this Policy or a successor privacy policy; and</li>
        <li>With your explicit consent or where you authorize sharing with third parties.</li>
      </ol>
    </li>
    <li>
      <p>We require third-party processors to implement appropriate safeguards (contractual protections, encryption, access controls) and to apply lawful transfer mechanisms for international data transfers.</p>
    </li>
  </ol>

  <h3>6. Data retention</h3>
  <ol>
    <li>
      <p>We retain personal data only as long as necessary to provide the Services and for legitimate business, legal, audit and compliance purposes. Typical retention periods include:</p>
      <ol type="A">
        <li><strong>Account and transaction data:</strong> retained for the duration of your account and, thereafter, for a period necessary to satisfy regulatory, accounting and dispute resolution obligations (commonly up to five years, unless a longer statutory period applies);</li>
        <li><strong>Support records and correspondence:</strong> retained as required to resolve issues and for quality assurance;</li>
        <li><strong>Analytics and logs:</strong> retained in anonymized or aggregated form to support product improvement.</li>
      </ol>
    </li>
    <li>
      <p>If you request deletion via in-app tools, we will delete or anonymize personal data unless retention is required by law or necessary for legitimate business purposes (for example, fraud prevention or legal claims).</p>
    </li>
  </ol>

  <h3>7. Your rights and choices</h3>
  <ol>
    <li>
      <p>Where applicable under local law, you may exercise the following rights regarding your personal data:</p>
      <ol type="A">
        <li><strong>Access:</strong> request a copy of the personal data we hold about you;</li>
        <li><strong>Correction:</strong> request correction of inaccurate or incomplete personal data;</li>
        <li><strong>Deletion:</strong> request deletion of personal data subject to legal retention obligations;</li>
        <li><strong>Portability:</strong> request a machine-readable copy of personal data you provided;</li>
        <li><strong>Restriction:</strong> request restriction of certain processing activities;</li>
        <li><strong>Objection:</strong> object to processing based on legitimate interest, including profiling; and</li>
        <li><strong>Withdraw consent:</strong> withdraw consent to processing where processing is consent-based.</li>
      </ol>
    </li>
    <li>
      <p>You may exercise these rights through available in-app mechanisms or the support and account controls offered within the Services. We will respond in accordance with applicable legal timelines.</p>
    </li>
  </ol>

  <h3>8. Security</h3>
  <ol>
    <li>
      <p>We maintain commercially reasonable technical and organizational measures designed to protect personal data against unauthorized access, disclosure, alteration or destruction. Measures include:</p>
      <ol type="A">
        <li>Encryption of data in transit and, where appropriate, at rest;</li>
        <li>Role-based access controls, authentication and least-privilege principles;</li>
        <li>Regular security testing, monitoring and vulnerability management;</li>
        <li>Secure hosting, logging and incident response procedures; and</li>
        <li>Contractual security obligations for third-party processors.</li>
      </ol>
    </li>
    <li>
      <p>No system is infallible. If a security incident affecting personal data occurs, we will take prompt remedial action and provide notice as required by law.</p>
    </li>
  </ol>

  <h3>9. Cookies, tracking and analytics</h3>
  <ol>
    <li>
      <p>Our website and selected app interfaces may use cookies, local storage and third-party analytics to enable essential functionality, monitor performance and improve the product.</p>
    </li>
    <li>
      <p>Where cookies are used for non-essential purposes (analytics or marketing), we obtain consent where required and provide mechanisms to manage preferences.</p>
    </li>
    <li>
      <p>You control cookie preferences via browser settings and available in-app or on-site controls.</p>
    </li>
  </ol>

  <h3>10. Cross-border transfers</h3>
  <ol>
    <li>
      <p>Stars Base operates internationally. Personal data may be processed or stored in jurisdictions outside your country of residence.</p>
    </li>
    <li>
      <p>For international transfers, we implement lawful transfer safeguards (adequacy findings, standard contractual clauses or equivalent measures) to ensure appropriate protection of personal data.</p>
    </li>
  </ol>

  <h3>11. Identity verification, KYC and compliance</h3>
  <ol>
    <li>
      <p>Where required by applicable law or for risk management, we may request identity verification or additional documentation.</p>
    </li>
    <li>
      <p>Identity data collected for compliance is processed securely and only for the purpose of meeting legal obligations. Failure to provide requested information may limit access to certain Services.</p>
    </li>
  </ol>

  <h3>12. Automated processing, risk scoring and AI</h3>
  <ol>
    <li>
      <p>We may use automated systems, algorithms and machine learning to support fraud detection, risk scoring, security operations and operational efficiency.</p>
    </li>
    <li>
      <p>Decisions that produce legal or similarly significant effects will include human review where required by law. You may challenge automated decisions and request human intervention where available under applicable law.</p>
    </li>
  </ol>

  <h3>13. Third-party links and integrations</h3>
  <ol>
    <li>
      <p>The Services may link to or integrate third-party services (including TON conversion partners). Third-party services have their own privacy practices; we are not responsible for their policies or practices.</p>
    </li>
    <li>
      <p>Before sharing personal data with third parties, review their privacy terms and data handling practices.</p>
    </li>
  </ol>

  <h3>14. Children</h3>
  <p>The Services are not directed to persons under 18. We do not knowingly collect personal data from children under 18. If we discover we have collected such data, we will take steps to delete it promptly.</p>

  <h3>15. Changes to this Privacy Policy</h3>
  <ol>
    <li>
      <p>We may update this Privacy Policy to reflect operational, legal or regulatory changes.</p>
    </li>
    <li>
      <p>If material changes occur, we will provide notice within the app or via the Services and update the “Last updated” date. Continued use of the Services after the effective date constitutes acceptance of the revised Policy.</p>
    </li>
  </ol>

  <h3>16. Miscellaneous</h3>
  <ol>
    <li>
      <p>This Privacy Policy complements other terms governing your use of Stars Base, including Terms of Service. In case of conflict, the relevant terms will indicate the governing document.</p>
    </li>
    <li>
      <p>Where permitted, we may aggregate or anonymize personal data and use aggregated data for analytics, research and product improvements.</p>
    </li>
    <li>
      <p>Nothing in this Privacy Policy creates contractual rights for third parties.</p>
    </li>
  </ol>

  <p>Thank you for using Stars Base. We are committed to maintaining strong privacy standards while delivering secure, transparent and high-quality staking services within Telegram.</p>
`;